"""Limites compartilhados pelo protocolo cliente-servidor."""

MAX_FILE_SIZE_BYTES = 20 * 1024 * 1024
MAX_FILENAME_SIZE_BYTES = 255

CONNECT_TIMEOUT_SECONDS = 5.0
SOCKET_IO_TIMEOUT_SECONDS = 60.0
SERVER_SESSION_TIMEOUT_SECONDS = 300.0
